services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - WATCHPACK_POLLING=true
      - HOSTNAME=0.0.0.0
      - PORT=3000
    restart: always
    networks:
      - app-network
    command: ['node', './server.js']

networks:
  app-network:
    driver: bridge
